### ISSUE TITLE
no phoenix downs/way to revive party members. 

### ISSUE THREAD

**Issue by TheBuffalax** [gameboy9/FF6KefkaRush#18]
i ended up with a seed where i have found no way to revive. no idea if that is by design or not

**Comment by gameboy9** [comment]
Monsters should be dropping Potions and Phoenix Downs throughout the game; all monsters have a 100% chance to drop an item, followed by a 20% chance of dropping a better item (typically a weapon, armor, or accessory).  If you see a monster dropping a Phoenix Down, you may want to write it down because it will always drop such an item.

Still, I think that there are better ways to distribute what items are dropped, so I'm going to take a look at that.

Maybe if the monster XP < 100, there's a 80% chance of a potion and a 20% chance of a phoenix down... if the XP < 250, there will be different chances, and so forth.

**Comment by gameboy9** [comment]
I resolved this in version 0.4.  (I think)  I'll reopen if I need to make drastic adjustments.
